pipeline:
  identifier: Build_nsengupta5_easy_node_docker_1736293306571
  name: Build easy-node-docker
  orgIdentifier: default
  projectIdentifier: Test
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: nsengupta5/easy-node-docker
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
            paths: []
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Background
                  name: Background
                  identifier: Background
                  spec:
                    connectorRef: dockerhub
                    image: docker:dind
                    shell: Sh
                    entrypoint:
                      - docker-entrypoint.sh
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    caching: true
                    connectorRef: <+input>
                    repo: hello/world
                    tags:
                      - latest
                  timeout: ""
                  type: BuildAndPushDockerRegistry
          sharedPaths:
            - /var/run
            - /var/lib/docker
          buildIntelligence:
            enabled: false
          platform:
            os: Linux
            arch: Arm64
          runtime:
            type: Docker
            spec: {}
        type: CI
        description: ""
        variables:
          - name: dh_pw
            type: Secret
            description: ""
            required: false
            value: dhpw
    - stage:
        name: Push
        identifier: Push
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
          buildIntelligence:
            enabled: true
          infrastructure:
            useFromStage: build
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: dockerpush
                  identifier: dockerpush
                  spec:
                    connectorRef: dockerhub
                    repo: nsengupta95/node-docker
                    tags:
                      - exampletag
                    caching: true
