pipeline:
  identifier: Build_nsengupta5_easy_node_docker_1736310081635
  name: Build easy-node-docker
  orgIdentifier: default
  projectIdentifier: HarnessDemo
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: nsengupta5/easy-node-docker
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    caching: true
                    connectorRef: <+input>
                    repo: hello/world
                    tags:
                      - latest
                  timeout: ""
                  type: BuildAndPushDockerRegistry
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: myconnector2
              namespace: default
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
        type: CI
    - stage:
        name: Push
        identifier: Push
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
          buildIntelligence:
            enabled: true
          infrastructure:
            useFromStage: build
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: pushimage
                  identifier: pushimage
                  spec:
                    connectorRef: docker_hub
                    repo: nsengupta95/node-docker
                    tags:
                      - exampletag
                    caching: true
