pipeline:
  identifier: Build_nsengupta5_easy_node_docker_1736284148566
  name: Build easy-node-docker
  orgIdentifier: default
  projectIdentifier: Test
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: nsengupta5/easy-node-docker
  stages:
    - stage:
        identifier: build
        name: Build
        spec:
          caching:
            enabled: true
            paths: []
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    caching: true
                    connectorRef: <+input>
                    repo: hello/world
                    tags:
                      - latest
                  timeout: ""
                  type: BuildAndPushDockerRegistry
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: thirdci
              namespace: default
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          buildIntelligence:
            enabled: false
        type: CI
        description: ""
    - stage:
        name: Push
        identifier: Push
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
          buildIntelligence:
            enabled: true
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Dockerhub
                  identifier: Dockerhub
                  spec:
                    connectorRef: dockerhub
                    repo: nsengupta95/node-docker
                    tags:
                      - exampletag
                    caching: true
          infrastructure:
            useFromStage: build
